name: release version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"

      - name: Create Package
        uses: benjefferies/create-bintray-package@master
        with:
          bintray-user: qcastel-yapily
          bintray-token: ${{ secrets.BINTRAY_ACCESS_TOKEN }}
          owner: qcastel-yapily
          repo: jose-database
          package-name: jose-database
          package-description: Encrypt/Sign your database fields using JWT format
          package-url: https://github.com/yapily/jose-database
          package-license: Apache-2.0

      - name: Temporarily disable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}
          owner: yapily
          enforce_admins: false
          repo: jose-database

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          maven-repo-server-id: bintray-jose-database-yapily
          maven-repo-server-username: qcastel-yapily
          maven-repo-server-password: ${{ secrets.PRIVATE_REPO_PASSWORD }}

          git-release-bot-name: "bot-yapily"
          git-release-bot-email: "bot@yapily.com"

          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}

      - name: Enable "include administrators" branch protection
        uses: benjefferies/branch-protection-bot@master
        if: always()
        with:
          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}
          owner: qcastel-yapily
          repo: jose-database