name: release version

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build and Test
        uses: qcastel/github-actions-maven-cmd@master
        with:
          maven-args: "clean install"

      - name: Release
        uses: qcastel/github-actions-maven-release@master
        with:
          maven-repo-server-id: bintray-jose-database-yapily
          maven-repo-server-username: qcastel-yapily
          maven-repo-server-password: ${{ secrets.PRIVATE_REPO_PASSWORD }}

          git-release-bot-name: "bot-yapily"
          git-release-bot-email: "bot@yapily.com"

          access-token: ${{ secrets.BOT_GITHUB_REPO_ACCESS_TOKEN }}
